name: Setup
description: Setup Action
runs:
  using: "composite"
  steps:
    - name: Setup Node LTS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0
        cache: yarn

    - name: Override default OS Typescript version
      run: npm install -g typescript@5.1.6
      shell: bash

    - name: Installing dependencies
      run: yarn install
      shell: bash
