name: Dependabot Automerge PRs
on:
  pull_request:
    branches:
      - main

jobs:
  dependabot-automerge-prs:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3