name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Fetch Git repository and checkout
        uses: "actions/checkout@v4"

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Override default OS Typescript version
        run: npm install -g typescript@5.1.6

      - name: Installing dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Type Checking
        run: yarn type-check